python -u run.py \
  --is_training 1 \
  --root_path data/stock \
  --data_path stock01.csv \
  --model_id stock01 \
  --model ns_Transformer \
  --data custom \
  --features M \
  --seq_len 30 \
  --label_len 0 \
  --pred_len 1 \
  --e_layers 16 \
  --d_layers 16 \
  --factor 3 \
  --enc_in 4 \
  --dec_in 4 \
  --c_out 4 \
  --gpu 0 \
  --des 'Exp_h256_l2' \
  --p_hidden_dims 256 256 \
  --p_hidden_layers 2 \
  --itr 1 &
